"""生成 dnsdist 规则 Lua (/etc/dnsdist/pdg-generated.lua)。

两种模式 (由 FINAL 策略的 dns_mode 决定):
  - 全代理 (FINAL→spoof): 默认 spoof, 仅排除 direct/block 域名。墙内推荐。
  - 白名单 (FINAL→direct): 只 spoof 显式列出的代理域名。

行为:
  spoof  → A 应答 JP 唯一内网 IP; AAAA → NODATA; HTTPS/SVCB → 空 NOERROR
  block  → NXDOMAIN (不分来源, 始终生效)
  direct → 落默认 pool 上游递归 (返回真实 IP)

若配置了 internal_src_cidr, spoof 仅对【来源在内网段】的查询生效;
其他来源(普通 WiFi)的代理域名查询落到上游 → 真实 IP → 手机直连 (自动降级)。

由主 dnsdist.conf 末尾 `dofile("/etc/dnsdist/pdg-generated.lua")` 引入。
目标: dnsdist 1.8+。生成后用 `dnsdist --check-config -C /etc/dnsdist/dnsdist.conf` 校验。
"""

from __future__ import annotations

import re
from datetime import datetime, timezone

from ..model import Config
from ..rules.compiler import CompiledTable


def _lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _suffix_node(var: str, names: list[str]) -> list[str]:
    lines = [f"local {var} = newSuffixMatchNode()"]
    for n in names:
        lines.append(f"{var}:add({_lua_str(n)})")
    return lines


def _keyword_regex(keywords: list[str], regexes: list[str]) -> str | None:
    """把 keyword(子串) 与 regex 合成一个 dnsdist 正则 (alternation)。"""
    parts = [re.escape(k) for k in keywords] + list(regexes)
    return "|".join(parts) if parts else None


def _and(*rules: str | None) -> str:
    """组合多个 dnsdist 规则为 AndRule。None 忽略; 全空 → AllRule()。"""
    rs = [r for r in rules if r]
    if not rs:
        return "AllRule()"
    if len(rs) == 1:
        return rs[0]
    return "AndRule({" + ", ".join(rs) + "})"


def _emit_block(out: list[str], modes: dict) -> None:
    block = modes["block"]
    block_suffixes = block["domain"] + block["domain_suffix"]
    if block_suffixes:
        out.append("-- ===== BLOCK → NXDOMAIN (始终生效) =====")
        out += _suffix_node("pdgBlock", block_suffixes)
        out.append("addAction(SuffixMatchNodeRule(pdgBlock), RCodeAction(DNSRCode.NXDOMAIN))")
        out.append("")
    block_kr = _keyword_regex(block["domain_keyword"], block["domain_regex"])
    if block_kr:
        out.append(f"addAction(RegexRule({_lua_str(block_kr)}), RCodeAction(DNSRCode.NXDOMAIN))")
        out.append("")


def _emit_spoof(out: list[str], config: Config, base_guards: list[str | None],
                base_rule: str | None) -> None:
    """发出 spoof 动作。base_guards: 前置门控(来源/NotRule等); base_rule: 主匹配器(后缀/正则/None)。"""
    https = _and(*base_guards, base_rule, "QTypeRule(DNSQType.HTTPS)")
    if config.proxy_block_https:
        out.append("-- HTTPS/SVCB 返回空 NOERROR (禁 ECH/HTTP3 协商), 必须排在 spoof 之前")
        out.append(f"addAction({https}, RCodeAction(DNSRCode.NOERROR))")
    if config.proxy_block_aaaa:
        # SpoofAction 只给 IPv4 → A 命中 JP IP, AAAA 自动 NODATA
        out.append(f"addAction({_and(*base_guards, base_rule)}, "
                   "SpoofAction({SPOOF_IP}, {ttl=TTL}))")
    else:
        out.append(f"addAction({_and(*base_guards, base_rule, 'QTypeRule(DNSQType.A)')}, "
                   "SpoofAction({SPOOF_IP}, {ttl=TTL}))")


def generate(table: CompiledTable, config: Config) -> str:
    modes = table.matchers_by_dns_mode()
    full_proxy = table.final_dns_mode == "spoof"
    out: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    out += [
        "-- AUTO-GENERATED by pdg — DO NOT EDIT.",
        f"-- generated: {ts}",
        f"-- 模式: {'全代理 (默认 spoof, 排除 direct/block)' if full_proxy else '白名单 (只 spoof 显式代理域名)'}",
        "-- 源: /etc/pdg/rules.conf (+ policies.conf)。改规则请编辑源文件后 `pdg reload`。",
        "-- 引入: 在主 dnsdist.conf 末尾添加 dofile(\"/etc/dnsdist/pdg-generated.lua\")",
        "",
        f"local SPOOF_IP = {_lua_str(config.jp_internal_ip)}",
        f"local TTL = {config.spoof_ttl}",
        "",
    ]

    src: str | None = None
    if config.internal_src_cidr:
        out.append("-- 内网来源段: 只有来自这些来源的代理域名才 spoof (其余来源 → 真实 IP 直连)")
        out.append("local pdgInternal = newNMG()")
        for cidr in config.internal_src_cidr:
            out.append(f"pdgInternal:addMask({_lua_str(cidr)})")
        out.append("")
        src = "NetmaskGroupRule(pdgInternal)"

    _emit_block(out, modes)

    if full_proxy:
        # 全代理: 默认 spoof, 排除 direct (block 已在前面终止)。
        out.append("-- ===== 全代理: 默认 spoof→JP, 排除 direct 域名 =====")
        direct = modes["direct"]
        direct_suffixes = direct["domain"] + direct["domain_suffix"]
        direct_kr = _keyword_regex(direct["domain_keyword"], direct["domain_regex"])
        guards: list[str | None] = [src]
        if direct_suffixes:
            out += _suffix_node("pdgDirect", direct_suffixes)
            guards.append("NotRule(SuffixMatchNodeRule(pdgDirect))")
        if direct_kr:
            guards.append(f"NotRule(RegexRule({_lua_str(direct_kr)}))")
        _emit_spoof(out, config, guards, None)
        out.append("")
        out.append("-- direct 域名 / 非内网来源 / 其余: 落上游 → 真实 IP")
    else:
        # 白名单: 只 spoof 显式代理域名。
        spoof = modes["spoof"]
        spoof_suffixes = spoof["domain"] + spoof["domain_suffix"]
        if spoof_suffixes:
            out.append("-- ===== 白名单 PROXY → A 应答 JP 内网 IP =====")
            out += _suffix_node("pdgProxy", spoof_suffixes)
            _emit_spoof(out, config, [src], "SuffixMatchNodeRule(pdgProxy)")
            out.append("")
        spoof_kr = _keyword_regex(spoof["domain_keyword"], spoof["domain_regex"])
        if spoof_kr:
            out.append("-- 白名单 PROXY (keyword/regex)")
            _emit_spoof(out, config, [src], f"RegexRule({_lua_str(spoof_kr)})")
            out.append("")
        out.append("-- DIRECT / 非内网来源 / 其余: 落上游 → 真实 IP")

    out.append("")
    return "\n".join(out)
